# Generated by Django 4.1.4 on 2022-12-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='numero_pasaporte',
            new_name='fecha_nacimiento',
        ),
    ]
